// Generated by Apple Swift version 4.2.1 effective-4.1.50 (swiftlang-1000.11.42 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreGraphics;
@import EVReflection;
@import FBSDKCoreKit;
@import FBSDKLoginKit;
@import FirebaseDatabase;
@import FirebaseMessaging;
@import Foundation;
@import GoogleMapsBase;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
#endif

#import <SnappersSDK/SnappersSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SnappersSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class CLLocation;
@class Config;

SWIFT_CLASS("_TtC11SnappersSDK3API")
@interface API : NSObject <FBSDKLoginButtonDelegate>
+ (void)warmup;
+ (void)objCGetAddresForLocation:(CLLocation * _Nonnull)location callback:(void (^ _Nullable)(NSError * _Nullable, NSString * _Nullable))callback;
+ (void)getConfigWithExperation:(NSTimeInterval)experation defaults:(NSDictionary<NSString *, NSObject *> * _Nullable)defaults callback:(void (^ _Nullable)(NSError * _Nullable, Config * _Nullable))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end







@class Reporter;

@interface API (SWIFT_EXTENSION(SnappersSDK))
+ (void)getReporterWithCallback:(void (^ _Nullable)(NSError * _Nullable, Reporter * _Nullable))callback;
+ (void)updateReporterObjcWithReporter:(Reporter * _Nonnull)reporter callback:(void (^ _Nullable)(NSError * _Nullable, Reporter * _Nullable))callback;
+ (void)updateFCMTokenWithReporter:(Reporter * _Nonnull)reporter callback:(void (^ _Nullable)(NSError * _Nullable, BOOL))callback;
@end

@class FIRDatabaseReference;

@interface API (SWIFT_EXTENSION(SnappersSDK))
+ (FIRDatabaseHandle)observerEventIsActiveWithEventRef:(FIRDatabaseReference * _Nonnull)eventRef callback:(void (^ _Nonnull)(BOOL))callback;
+ (void)unobserveEventIsActiveWithEventRef:(FIRDatabaseReference * _Nonnull)eventRef handle:(FIRDatabaseHandle)handle;
@end

@class FBSDKLoginButton;
@class FBSDKLoginManagerLoginResult;

@interface API (SWIFT_EXTENSION(SnappersSDK))
- (void)loginButton:(FBSDKLoginButton * _Null_unspecified)loginButton didCompleteWithResult:(FBSDKLoginManagerLoginResult * _Null_unspecified)result error:(NSError * _Null_unspecified)error;
- (void)loginButtonDidLogOut:(FBSDKLoginButton * _Null_unspecified)loginButton;
+ (void)signout:(void (^ _Nullable)(NSError * _Nullable))callback;
@end


SWIFT_CLASS("_TtC11SnappersSDK9Affiliate")
@interface Affiliate : EVObject
@property (nonatomic, copy) NSString * _Nullable signUpCode;
- (BOOL)skipPropertyValue:(id _Nonnull)value key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;
@class UINavigationController;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC11SnappersSDK28AffiliateLoginViewController")
@interface AffiliateLoginViewController : UIViewController <UINavigationControllerDelegate, UITextFieldDelegate>
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (void)viewWillDisappear:(BOOL)animated;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)showCoverWithAnimate:(BOOL)animate callback:(void (^ _Nullable)(void))callback;
- (void)hideCover;
@property (nonatomic, readonly) UIInterfaceOrientation preferredInterfaceOrientationForPresentation;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) BOOL shouldAutorotate;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (void)navigationController:(UINavigationController * _Nonnull)navigationController didShowViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated;
- (BOOL)prefersHomeIndicatorAutoHidden SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

enum AnalyticsEventLevel : NSInteger;

SWIFT_CLASS("_TtC11SnappersSDK9Analytics")
@interface Analytics : NSObject
+ (void)configure;
+ (void)sendEventObjCWithName:(NSString * _Nonnull)name data:(NSDictionary<NSString *, id> * _Nullable)data level:(enum AnalyticsEventLevel)level;
+ (void)sendBroadcastStarted;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, AnalyticsEventLevel, closed) {
  AnalyticsEventLevelError = 0,
  AnalyticsEventLevelWarning = 1,
  AnalyticsEventLevelInfo = 2,
};


SWIFT_CLASS("_TtC11SnappersSDK14ChatBubbleCell")
@interface ChatBubbleCell : UITableViewCell
@property (nonatomic) CGFloat requiredCellHight;
@property (nonatomic) BaloonsLayout layout;
@property (nonatomic, copy) NSString * _Nullable message;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SnappersSDK6Config")
@interface Config : EVObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull termsAndConditionsURL;)
+ (NSString * _Nonnull)termsAndConditionsURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultEventTableImageName;)
+ (NSString * _Nonnull)defaultEventTableImageName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultEventMapImageName;)
+ (NSString * _Nonnull)defaultEventMapImageName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultProfilePictureURL;)
+ (NSString * _Nonnull)defaultProfilePictureURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull mapStyle;)
+ (NSString * _Nonnull)mapStyle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull defaultWelconeMessage;)
+ (NSString * _Nonnull)defaultWelconeMessage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval time_waste_before_updating_event_list;)
+ (NSTimeInterval)time_waste_before_updating_event_list SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger speed_test_total_pings;)
+ (NSInteger)speed_test_total_pings SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval speed_test_ping_timeout_in_seconds;)
+ (NSTimeInterval)speed_test_ping_timeout_in_seconds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval speedTestTimeLimitInSeconds;)
+ (NSTimeInterval)speedTestTimeLimitInSeconds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger max_broadcast_recovery_tries;)
+ (NSInteger)max_broadcast_recovery_tries SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval end_recording_time_in_seconds;)
+ (NSTimeInterval)end_recording_time_in_seconds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval chatIdleTimeBeforeHiding;)
+ (NSTimeInterval)chatIdleTimeBeforeHiding SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull videoRecorderClassName;)
+ (NSString * _Nonnull)videoRecorderClassName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amazonUploadBucket;)
+ (NSString * _Nonnull)amazonUploadBucket SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amazonKey;)
+ (NSString * _Nonnull)amazonKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amazonSecret;)
+ (NSString * _Nonnull)amazonSecret SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amazonPoolID;)
+ (NSString * _Nonnull)amazonPoolID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amazonAffiliateProductionUploadPath;)
+ (NSString * _Nonnull)amazonAffiliateProductionUploadPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amazonAffiliateStagingUploadPath;)
+ (NSString * _Nonnull)amazonAffiliateStagingUploadPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amazonProductionUploadPath;)
+ (NSString * _Nonnull)amazonProductionUploadPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull amazonStagingUploadPath;)
+ (NSString * _Nonnull)amazonStagingUploadPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) double maxVideoFileSizeInMegs;)
+ (double)maxVideoFileSizeInMegs SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSTimeInterval reporterLocationUpdateIntervalInSeconds;)
+ (NSTimeInterval)reporterLocationUpdateIntervalInSeconds SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger emailPasswordMinNumberOfCharacters;)
+ (NSInteger)emailPasswordMinNumberOfCharacters SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC11SnappersSDK4Drop")
@interface Drop : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end





enum DropStateObjC : NSInteger;

@interface Drop (SWIFT_EXTENSION(SnappersSDK))
+ (void)downObjc:(NSString * _Nonnull)status state:(enum DropStateObjC)state duration:(double)duration action:(void (^ _Nullable)(void))action;
@end

typedef SWIFT_ENUM(NSInteger, DropStateObjC, closed) {
  DropStateObjCObjcInfo = 0,
  DropStateObjCObjcSuccess = 1,
  DropStateObjCObjcWarning = 2,
  DropStateObjCObjcError = 3,
};


SWIFT_CLASS("_TtC11SnappersSDK5Event")
@interface Event : EVObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable wellcomeMessage;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (BOOL)skipPropertyValue:(id _Nonnull)value key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SnappersSDK13EventProvider")
@interface EventProvider : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





@class UIButton;
@class HUDItem;

SWIFT_CLASS("_TtC11SnappersSDK3HUD")
@interface HUD : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HUD * _Nonnull shared;)
+ (HUD * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified itemContainer;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified closeButton;
@property (nonatomic, strong) HUDItem * _Nullable currentItem;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)layoutSubviews;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)hideWithName:(NSString * _Nullable)name animated:(BOOL)animated callback:(void (^ _Nullable)(void))callback;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIColor;

SWIFT_CLASS("_TtC11SnappersSDK7HUDItem")
@interface HUDItem : UIView
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic) BOOL showCover;
@property (nonatomic, strong) UIColor * _Nonnull coverColor;
@property (nonatomic) CGFloat coverAlpha;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) UIColor * _Nonnull titleBackgroundColor;
@property (nonatomic) BOOL closeButton;
@property (nonatomic, copy) void (^ _Nullable closeButtonCallback)(void);
- (HUDItem * _Nonnull)showWithAnimated:(BOOL)animated parentView:(UIView * _Nullable)parentView callback:(void (^ _Nullable)(void))callback;
- (void)hideWithAnimated:(BOOL)animated callback:(void (^ _Nullable)(void))callback;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SnappersSDK8Location")
@interface Location : EVObject
@property (nonatomic, copy) NSString * _Nullable fullName;
@property (nonatomic) double lat;
@property (nonatomic) double lng;
- (BOOL)skipPropertyValue:(id _Nonnull)value key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SnappersSDK35LocationAuthorizationViewController")
@interface LocationAuthorizationViewController : UIViewController <UITextViewDelegate>
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)handleAppMovedToForeground;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SnappersSDK12LocationData")
@interface LocationData : EVObject
@property (nonatomic, strong) Location * _Nonnull lastKnown;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC11SnappersSDK18OrientationManager")
@interface OrientationManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OrientationManager * _Nonnull shared;)
+ (OrientationManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)resume;
- (void)resign;
@end


SWIFT_CLASS("_TtC11SnappersSDK8Reporter")
@interface Reporter : EVObject
@property (nonatomic, copy) NSString * _Nullable img;
@property (nonatomic, copy) NSString * _Nullable FCMToken;
@property (nonatomic, strong) LocationData * _Nullable locationData;
- (BOOL)skipPropertyValue:(id _Nonnull)value key:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)objcSetIsAnonymous:(BOOL)bool_;
- (void)objcSetIsAppUser:(BOOL)bool_;
- (NSString * _Nonnull)getID SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class StreamingServer;

SWIFT_CLASS("_TtC11SnappersSDK10Repository")
@interface Repository : EVObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Repository * _Nonnull shared;)
+ (Repository * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) Affiliate * _Nullable affiliate;
@property (nonatomic, copy) NSURL * _Nullable lastOpenedLink;
@property (nonatomic, strong) Reporter * _Nullable reporter;
@property (nonatomic, strong) StreamingServer * _Nullable server;
@property (nonatomic, copy) NSString * _Nullable clientID;
@property (nonatomic, copy) NSString * _Nullable clientKey;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable invitationData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)versionSigniture SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11SnappersSDK11SnappersSDK")
@interface SnappersSDK : NSObject <FIRMessagingDelegate, UIApplicationDelegate, UNUserNotificationCenterDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class FIRMessaging;
@class FIRMessagingRemoteMessage;

@interface SnappersSDK (SWIFT_EXTENSION(SnappersSDK))
- (void)messaging:(FIRMessaging * _Nonnull)messaging didReceiveRegistrationToken:(NSString * _Nonnull)fcmToken;
- (void)messaging:(FIRMessaging * _Nonnull)messaging didReceiveMessage:(FIRMessagingRemoteMessage * _Nonnull)remoteMessage;
@end



@class UNUserNotificationCenter;
@class UNNotificationResponse;
@class UNNotification;

@interface SnappersSDK (SWIFT_EXTENSION(SnappersSDK))
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceiveNotificationResponse:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center openSettingsForNotification:(UNNotification * _Nullable)notification;
- (void)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center willPresentNotification:(UNNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(UNNotificationPresentationOptions))completionHandler;
@end

@class UIApplication;

@interface SnappersSDK (SWIFT_EXTENSION(SnappersSDK))
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation SWIFT_WARN_UNUSED_RESULT;
@end


@interface SnappersSDK (SWIFT_EXTENSION(SnappersSDK))
- (void)application:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
@end


SWIFT_CLASS("_TtC11SnappersSDK15StreamingServer")
@interface StreamingServer : EVObject
@property (nonatomic, copy) NSString * _Null_unspecified region;
@property (nonatomic, copy) NSString * _Null_unspecified speedTestServer;
@property (nonatomic, copy) NSString * _Null_unspecified streamingServer;
@property (nonatomic, copy) NSString * _Null_unspecified viewingServer;
@property (nonatomic) double uploadSpeed;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (void)reset;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface UIColor (SWIFT_EXTENSION(SnappersSDK))
- (NSString * _Nonnull)colorDescription SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIColor (SWIFT_EXTENSION(SnappersSDK))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull snappersMain;)
+ (UIColor * _Nonnull)snappersMain SWIFT_WARN_UNUSED_RESULT;
+ (void)setSnappersMain:(UIColor * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersBackground;)
+ (UIColor * _Nonnull)snappersBackground SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snapersVendor;)
+ (UIColor * _Nonnull)snapersVendor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersChatBallonClient;)
+ (UIColor * _Nonnull)snappersChatBallonClient SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersChatBallonManager;)
+ (UIColor * _Nonnull)snappersChatBallonManager SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersChatBallonTextClient;)
+ (UIColor * _Nonnull)snappersChatBallonTextClient SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersChatBallonTextManager;)
+ (UIColor * _Nonnull)snappersChatBallonTextManager SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersBroadCastButton;)
+ (UIColor * _Nonnull)snappersBroadCastButton SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersLocateButton;)
+ (UIColor * _Nonnull)snappersLocateButton SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersMarkerRadius;)
+ (UIColor * _Nonnull)snappersMarkerRadius SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersMarkerBackgrund;)
+ (UIColor * _Nonnull)snappersMarkerBackgrund SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersSendButton;)
+ (UIColor * _Nonnull)snappersSendButton SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull snappersEmailAuth;)
+ (UIColor * _Nonnull)snappersEmailAuth SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nonnull)fromNumber:(uint32_t)number SWIFT_WARN_UNUSED_RESULT;
+ (UIColor * _Nullable)fromHexString:(NSString * _Nonnull)hexString error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) CGFloat brightness;
@end










SWIFT_CLASS("_TtC11SnappersSDK5Utils")
@interface Utils : NSObject
+ (void)supressEVReflectionsLogs;
+ (NSString * _Nonnull)removeWhiteSpacesFromEndOfString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
